---
- set_fact:
    username: "{{ __username|list }}"
  when: username|default(None) == None

- set_fact:
    nopassword: "{{ __nopassword }}"
  when: nopassword|default(None) == None

- apt:
    name: sudo

- template:
    src: "{{ distribution_codename }}/etc/sudoers.d/username-nopassword-all.j2"
    dest: /etc/sudoers.d/ansible-{{ username }}"
    mode: 440
    owner: root
    group: root
  when: nopassword is defined and nopassword

- set_fact:
    username: !!null
    nopassword: !!null

